os: linux
language: php
dist: bionic
env:
  global:
    - XDEBUG_MODE=coverage
    - PGPORT=5432
    - PGHOST=localhost
    - PGDATABASE=dbd_tests
    - PGUSER=postgres

addons:
  apt:
    packages:
      - php-pgsql
      - php-memcache
      - postgresql-11
      - postgresql-client-11

services:
  - postgresql
  - memcached

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

before_script:
  - psql -c 'create database $PGDATABASE;' -U $PGUSER
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - psql -c 'drop database $PGDATABASE;' -U $PGUSER
  - vendor/bin/php-coveralls --verbose
